# Parámetros para el Pipeline de Limpieza
cleaning:
  # Proporción para el método IQR
  outlier_threshold: 1.5
  # Valores por defecto para nulos
  default_category: "Sin Asignar"
  default_binary: "No"

# Parámetros para el Pipeline de Transformación
transform:
  # Columnas para los joins
  primary_key: "id_empleado"
  # Columnas para promediar en evaluaciones
  evaluation_metrics:
    - "puntaje_desempeno"
    - "competencias_tecnicas"
    - "competencias_blandas"

# Parámetros para los Pipelines de Machine Learning
ml:
  # División train/test
  test_size: 0.2

  # Validación cruzada
  cv_folds: 5

  # PCA
  pca_n_components: 2

  # K-Means
  kmeans_n_clusters: 3
  kmeans_max_k: 8

  # RandomizedSearchCV
  random_search_n_iter: 20
